// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjDzIh3WhNzPsQWJrwli7QaOTOeDIU7Sw',
    appId: '1:225413271858:web:4937076d5edd982121472b',
    messagingSenderId: '225413271858',
    projectId: 'skillspark-d2983',
    authDomain: 'skillspark-d2983.firebaseapp.com',
    storageBucket: 'skillspark-d2983.appspot.com',
    measurementId: 'G-YZB453DB6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgP8EKkh_Axcfte9yctJFNimKGTSDA82Y',
    appId: '1:225413271858:android:de39d8a63725a9ba21472b',
    messagingSenderId: '225413271858',
    projectId: 'skillspark-d2983',
    storageBucket: 'skillspark-d2983.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBess3q6HRQXk9mVq6DvjErD71Kvj0J3bw',
    appId: '1:225413271858:ios:28a867cf7cd77d6821472b',
    messagingSenderId: '225413271858',
    projectId: 'skillspark-d2983',
    storageBucket: 'skillspark-d2983.appspot.com',
    iosBundleId: 'com.example.miniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBess3q6HRQXk9mVq6DvjErD71Kvj0J3bw',
    appId: '1:225413271858:ios:514363d04f70762521472b',
    messagingSenderId: '225413271858',
    projectId: 'skillspark-d2983',
    storageBucket: 'skillspark-d2983.appspot.com',
    iosBundleId: 'com.example.miniProject.RunnerTests',
  );
}
